/* Conoce: native SVG controls, source filters and a report of the actual catalog. */
(() => {
  'use strict';
  const root=document.getElementById('data-conoce'); if(!root)return;
  const paths={priorizar:'M6 3h12v18H6z M9 7h6 M9 11h6 M9 15h6',integrar:'m12 3 10 5-10 5L2 8z M2 12l10 5 10-5 M2 16l10 5 10-5',validar:'M8 14c-4 0-6 2-6 6h12c0-4-2-6-6-6Z M18 14c3 0 4 2 4 6h-5 M8 4a4 4 0 1 0 0 8 4 4 0 0 0 0-8Z M18 5a3 3 0 1 0 0 6',estandarizar:'m9 3-1 3-3 1-2 3 2 2-1 3 3 2 1 3h4l1-3 3-1 2-3-2-2 1-3-3-2-1-3Z M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8Z',fortalecer:'M3 13h4v8H3z M10 8h4v13h-4z M17 3h4v18h-4z',fuentes:'M3 6c0-4 18-4 18 0s-18 4-18 0Z M3 6v12c0 4 18 4 18 0V6 M3 12c0 4 18 4 18 0',recopilacion:'M5 2h10l5 5v15H5Z M15 2v6h5 M8 12h9 M8 16h9',validacion:'M12 2 3 6v7c0 5 9 9 9 9s9-4 9-9V6Z m-5 10 3 3 7-7',organizacion:'M3 6c0-4 18-4 18 0s-18 4-18 0Z M3 6v12c0 4 18 4 18 0V6 M3 12c0 4 18 4 18 0',analisis:'M3 13h4v8H3z M10 8h4v13h-4z M17 3h4v18h-4z',decision:'M9 18h6 M9 21h6 M8 15c-7-8 1-17 8-11 4 4 2 7 0 11l-1 3H9Z',cobertura:'M12 2 3 6v7c0 5 9 9 9 9s9-4 9-9V6Z M8 11h8 M12 7v9',periodicidad:'M3 5h18v16H3Z M7 2v6 M17 2v6 M3 10h18 M7 14h3 M14 14h3',actualizacion:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Z M12 6v6l4 3'};
  function icon(key){return `<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[key]}"></path></svg>`;}
  const principles=[
    {label:'Priorizar',key:'priorizar',angle:-90,title:'Priorizar la información crítica',text:'Concentrar el esfuerzo en variables esenciales para construir una base mínima confiable que ayude a tomar decisiones.'},
    {label:'Integrar',key:'integrar',angle:-162,title:'Integrar fuentes diversas',text:'Articular fuentes nacionales, departamentales, municipales y comunitarias, aunque provengan de formatos distintos.'},
    {label:'Validar',key:'validar',angle:-18,title:'Validar con el territorio',text:'Contrastar la información con la comunidad y los actores locales antes de usarla.'},
    {label:'Estandarizar',key:'estandarizar',angle:54,title:'Documentar y estandarizar',text:'Registrar el origen, clasificar y actualizar cada dato con protocolos claros que eviten pérdida de información.'},
    {label:'Fortalecer',key:'fortalecer',angle:126,title:'Fortalecer capacidades locales',text:'Formar equipos municipales y comunitarios en interpretación de datos y herramientas para sostener la gestión de información.'}
  ];
  const wheel=root.querySelector('#statisticsWheel');
  const polar=(r,a)=>[170+r*Math.cos(a*Math.PI/180),170+r*Math.sin(a*Math.PI/180)];
  const xy=p=>p.map(v=>v.toFixed(2)).join(',');
  function rounded(points){const corners=points.map((p,i)=>{const prev=points[(i+points.length-1)%points.length],next=points[(i+1)%points.length];const near=q=>{const d=Math.hypot(q[0]-p[0],q[1]-p[1]),t=Math.min(11/d,.18);return [p[0]+(q[0]-p[0])*t,p[1]+(q[1]-p[1])*t];};return {p,a:near(prev),b:near(next)};});return 'M'+xy(corners[0].a)+corners.map((c,i)=>(i?' L'+xy(c.a):'')+' Q'+xy(c.p)+' '+xy(c.b)).join('')+' Z';}

  const defs=principles.map(p=>`<symbol id="cn-icon-${p.key}" viewBox="0 0 24 24"><path d="${paths[p.key]}" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></symbol>`).join('');
  wheel.innerHTML=`<defs>${defs}</defs><defs><clipPath id="cn-center-clip"><circle cx="170" cy="170" r="53"/></clipPath></defs><circle cx="170" cy="170" r="62" fill="#162d3e" stroke="#547b98" stroke-width="5"/><image href="assets/img/conoce/propuesta-aprobada.webp" x="-308" y="-748" width="887" height="1774" clip-path="url(#cn-center-clip)" aria-hidden="true"/>`+principles.map((p,i)=>{const a=p.angle; const points=[polar(158,a-26),polar(168,a),polar(158,a+26),polar(79,a+29),polar(79,a-29)];const [x,y]=polar(119,a);return `<g class="cn-petal ${i===2?'active':''}" role="button" tabindex="0" aria-label="${i+1}. ${p.label}" aria-pressed="${i===2}" aria-controls="statisticsNote" data-principle="${i}"><path d="${rounded(points)}" stroke-linejoin="round"/><text x="${x}" y="${y-17}" text-anchor="middle" font-size="17" font-weight="700">${String(i+1).padStart(2,'0')}</text><text x="${x}" y="${y+1}" text-anchor="middle" font-size="13" font-weight="600">${p.label}</text><use href="#cn-icon-${p.key}" x="${x-12}" y="${y+10}" width="24" height="24"/></g>`;}).join('');
  const note=root.querySelector('#statisticsNote');let selected=2;
  function select(index){selected=index;wheel.querySelectorAll('[data-principle]').forEach((el,i)=>{el.classList.toggle('active',i===index);el.setAttribute('aria-pressed',String(i===index));});root.querySelector('#cn-note-title').textContent=principles[index].title;root.querySelector('#cn-note-copy').textContent=principles[index].text;note.hidden=false;}
  wheel.addEventListener('click',e=>{const el=e.target.closest('[data-principle]');if(el)select(Number(el.dataset.principle));});
  wheel.addEventListener('keydown',e=>{const el=e.target.closest('[data-principle]');if(!el)return;const i=Number(el.dataset.principle);if(e.key==='Enter'||e.key===' '){e.preventDefault();select(i);}if(['ArrowRight','ArrowDown','ArrowLeft','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?4:(i+(['ArrowRight','ArrowDown'].includes(e.key)?1:4))%5;wheel.querySelector(`[data-principle="${n}"]`).focus();select(n);}if(e.key==='Escape')note.hidden=true;});
  root.querySelector('.cn-note-close').addEventListener('click',()=>{note.hidden=true;wheel.querySelector(`[data-principle="${selected}"]`).focus();});
  root.querySelector('#cn-process-steps').innerHTML=[['fuentes','Fuentes'],['recopilacion','Recopilación'],['validacion','Validación'],['organizacion','Organización'],['analisis','Análisis'],['decision','Decisión']].map(([k,n])=>`<li><span class="cn-step-icon">${icon(k)}</span><span>${n}</span></li>`).join('');
  const sources=[
    {id:'dane',name:'DANE',type:'Estadísticas oficiales',sector:'estadistica',level:'nacional',description:'Entidad que produce y difunde información estadística oficial del país en temas de población, economía, sociedad y ambiente.',url:'https://www.dane.gov.co/'},
    {id:'igac',name:'IGAC',type:'Información geográfica',sector:'geografia',level:'nacional',description:'Entidad que produce información geográfica, cartográfica y catastral del territorio colombiano.',url:'https://www.igac.gov.co/'},
    {id:'sui',name:'SUI',type:'Servicios públicos',sector:'servicios',level:'nacional',description:'Sistema Único de Información de servicios públicos domiciliarios, con información del sector de agua, saneamiento, energía y gas.',url:'https://sui.superservicios.gov.co/'}
  ];
  const search=root.querySelector('#cn-source-search'),level=root.querySelector('#cn-source-level'),sector=root.querySelector('#cn-source-sector');
  const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  function filtered(){const q=normalize(search.value);return sources.filter(s=>(!level.value||s.level===level.value)&&(!sector.value||s.sector===sector.value)&&normalize([s.name,s.type,s.description].join(' ')).includes(q));}
  function render(){const items=filtered();root.querySelector('#cn-source-cards').innerHTML=items.map(s=>`<article class="cn-card"><div class="cn-card-head"><span class="cn-logo ${s.id}" aria-label="${s.name}">${s.name}</span><div><h3>${s.name}</h3><p>${s.type}</p></div></div><p class="cn-card-description">${s.description}</p><dl class="cn-metadata">${[['cobertura','Cobertura:'],['periodicidad','Periodicidad:'],['actualizacion','Actualización:']].map(([k,n])=>`<div>${icon(k)}<dt>${n}</dt><dd>por verificar</dd></div>`).join('')}</dl><a href="${s.url}" target="_blank" rel="noopener noreferrer" class="cn-text-link" aria-label="Consultar fuente oficial ${s.name}, abre otra pestaña">Consultar fuente ↗</a></article>`).join('');root.querySelector('#cn-source-empty').hidden=!!items.length;}
  search.addEventListener('input',render);level.addEventListener('change',render);sector.addEventListener('change',render);
  root.querySelector('#cn-show-catalog').addEventListener('click',()=>{search.value='';level.value='';sector.value='';render();search.focus();});
  root.querySelector('#cn-download').addEventListener('click',()=>{const rows=[['Entidad','Descripción','Fuente oficial','Nivel territorial','Cobertura','Periodicidad','Fecha de actualización','Estado de validación'],...filtered().map(s=>[s.name,s.type,s.url,s.level,'Por verificar','Por verificar','Por verificar','Pendiente de validar'])];const csv='\uFEFF'+rows.map(row=>row.map(v=>'"'+v.replaceAll('"','""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='fuentes-data-territorio.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
  render();
})();
