/* End-to-end browser smoke for Memoria de la Alcaldía. Uses fictional test files ONLY during test, never deployed. */
'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const http=require('node:http');
const {chromium}=require('playwright');
const base=path.resolve(__dirname,'..');
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.geojson':'application/geo+json','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml','.woff2':'font/woff2'};
const server=http.createServer((req,res)=>{
 const p=decodeURIComponent((req.url||'/').split('?')[0]);
 const abs=path.resolve(base,p==='/'?'index.html':p.replace(/^\/+/,''));
 if(!abs.startsWith(base+path.sep)){res.writeHead(403).end();return;}
 fs.stat(abs,(err,st)=>{if(err||!st.isFile()){res.writeHead(404).end('Not found');return;}
 res.writeHead(200,{'Content-Type':types[path.extname(abs)]||'application/octet-stream'});fs.createReadStream(abs).pipe(res);});
});
async function run(){
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const host='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1,acceptDownloads:true});
 const errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const shots=path.join(base,'screenshots');fs.mkdirSync(shots,{recursive:true});
 try{
 await page.goto(host+'/#data?seccion=data-municipales',{waitUntil:'domcontentloaded',timeout:45000});
 await page.locator('#maApp[data-ready="true"]').waitFor({timeout:25000});
 await page.locator('#maTitle').waitFor({state:'visible'});
 assert.equal(await page.locator('.ma-feature').count(),4);
 assert.equal(await page.locator('#maLegacyWorkspace .dataset-workspace').count(),1);
 assert.match(await page.locator('#maApp').innerText(),/Repositorio de trabajo/);
 assert.equal(await page.locator('.ma-doc-table').count(),0);
 const metrics=await page.evaluate(()=>{
   const hero=document.querySelector('#data-municipales .ma-hero').getBoundingClientRect();
   const nav=document.querySelector('#siteHeader').getBoundingClientRect();
   const cards=document.querySelector('#data-municipales .ma-features').getBoundingClientRect();
   const analytics=document.querySelector('#data-municipales .ma-grid-analytics').getBoundingClientRect();
   const finalRow=document.querySelector('#data-municipales .ma-grid-doc-history').getBoundingClientRect();
   const general=document.querySelector('.app-view.active[data-view=data] > .view-hero');
   return {header:nav.height,heroTop:hero.top,heroHeight:hero.height,cardsTop:cards.top,analyticsTop:analytics.top,finalTop:finalRow.top,heroVisible:getComputedStyle(general).display!=='none', width:window.innerWidth, docWidth:document.documentElement.scrollWidth};
 });
 assert.ok(metrics.heroTop < metrics.header+12,'2.3 is obstructed by the general Data Territorio hero: '+JSON.stringify(metrics));
 assert.ok(!metrics.heroVisible,'Generic Data hero must be hidden on 2.3');
 assert.ok(metrics.heroHeight>=320&&metrics.heroHeight<=340,'Hero must reproduce 328 px composition');
 assert.ok(metrics.cardsTop>=metrics.heroTop+metrics.heroHeight-3&&metrics.cardsTop<=metrics.heroTop+metrics.heroHeight+7,'Four cards must follow hero without search bar');
 assert.ok(metrics.analyticsTop<metrics.heroTop+metrics.heroHeight+140,'Three analytical panels must immediately follow the four cards');
 assert.ok(metrics.finalTop>metrics.analyticsTop&&metrics.finalTop<metrics.heroTop+metrics.heroHeight+380,'Historical timeline must be within reference first fold');
 assert.ok(metrics.docWidth<=metrics.width+5,'Desktop horizontal overflow');
 assert.equal(await page.locator('#data-municipales .ma-grid-analytics > .ma-panel').count(),3);
 assert.equal(await page.locator('#data-municipales .ma-grid-doc-history > .ma-panel').count(),2);
 assert.equal(await page.locator('#data-municipales video').count(),0,'Never embed Mayor video');
 assert.equal(await page.locator('#data-municipales iframe').count(),0,'Never embed Mayor video');
 await page.screenshot({path:path.join(shots,'memoria23-vacia.png'),fullPage:true});
 await page.locator('[data-ma-action="new"]').first().click();
 await page.locator('#maUploadForm [name="title"]').fill('Acta de prueba — No oficial');
 await page.locator('#maUploadForm [name="type"]').selectOption('Acta');
 await page.locator('#maUploadForm [name="dependency"]').fill('Secretaría de Pruebas');
 await page.locator('#maUploadForm [name="dated"]').fill('2021-04-12');
 await page.locator('#maUploadForm [name="source"]').fill('Archivo de pruebas del navegador');
 await page.locator('#maUploadForm [name="summary"]').fill('Contenido generado solo durante la prueba automatizada');
 await page.locator('#maUploadForm [name="historic"]').selectOption('true');
 await page.locator('#maUploadForm input[type=file]').setInputFiles({name:'acta-de-prueba.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n% Test fixture\n%%EOF')});
 await page.locator('#maUploadForm button[type=submit]').click();
 await page.locator('#maApp[data-ready=true]').waitFor({state:'visible'});
 await page.locator('#maFormDialog').waitFor({state:'hidden'});
 assert.equal(await page.locator('.ma-doc-table tbody tr').count(),1);
 assert.equal(await page.locator('.ma-doc-table tbody tr').count(),1);
 await page.locator('[data-ma-action="new"]').first().click();
 await page.locator('#maUploadForm [name=title]').fill('Referencia física de prueba');
 await page.locator('#maUploadForm [name=type]').selectOption('Informe');
 await page.locator('#maUploadForm [name=dependency]').fill('Dependencia de pruebas');
 await page.locator('#maUploadForm [name=dated]').fill('1999-01-10');
 await page.locator('#maUploadForm [name=source]').fill('Registro físico de prueba');
 await page.locator('#maUploadForm [name=historic]').selectOption('true');
 await page.locator('#maUploadForm [name=status]').selectOption('physical');
 await page.locator('#maUploadForm button[type=submit]').click();
 await page.locator('#maFormDialog').waitFor({state:'hidden'});
 await page.locator('.ma-feature[data-ma-mode="documents"]').waitFor({state:'visible'});
 assert.equal(await page.locator('.ma-doc-table tbody tr').count(),2);
 await page.locator('[data-ma-mode="overview"]').click();
 assert.equal(await page.locator('.ma-doc-table tbody tr').count(),2);
 assert.equal(await page.locator('svg.ma-chart').count(),1);
 assert.ok(await page.locator('.ma-donut').count()>=1);
 assert.match(await page.locator('.ma-key-metrics').innerText(),/2/);
 await page.screenshot({path:path.join(shots,'memoria23-con-registros-locales.png'),fullPage:true});
 await page.locator('[data-ma-action="search"]').click();
 await page.locator('.ma-search [name=q]').fill('Acta de prueba');
 await page.locator('.ma-search-btn').click();
 assert.match(await page.locator('.ma-search-meta').innerText(),/1 resultado/);
 await page.locator('[data-ma-action="clear"]').click();
 const download=page.waitForEvent('download');
 await page.locator('[data-ma-action="export"]').click();
 assert.match((await download).suggestedFilename(),/catalogo-local\.csv$/);
 await page.locator('[data-ma-mode="series"]').click();
 assert.match(await page.locator('#maSectionTitle').innerText(),/Series históricas/);
 await page.locator('[data-ma-mode="history"]').click();
 assert.match(await page.locator('#maSectionTitle').innerText(),/Inventario histórico/);
 assert.match(await page.locator('.ma-timeline').innerText(),/2021|1999/);
 await page.locator('[data-ma-mode="dependencies"]').click();
 assert.equal(await page.locator('.ma-dep-card').count(),2);
 await page.locator('.ma-dep-card').first().click();
 assert.equal(await page.locator('.ma-doc-table tbody tr').count(),1);
 await page.locator('[data-ma-action="clear"]').click();
 await page.locator('.ma-doc-title').first().click();
 await page.locator('#maDetailDialog').waitFor({state:'visible'});
 assert.match(await page.locator('#maDetailDialog').innerText(),/Fuente|Procedencia/);
 await page.locator('#maDetailDialog [data-ma-action=edit]').click();
 await page.locator('#maUploadForm [name=summary]').fill('Resumen modificado en prueba');
 await page.locator('#maUploadForm button[type=submit]').click();
 await page.locator('#maFormDialog').waitFor({state:'hidden'});
 await page.locator('.ma-doc-title').first().click();
 assert.match(await page.locator('#maDetailDialog').innerText(),/Resumen modificado en prueba/);
 await page.locator('#maDetailDialog [data-ma-action=close]').click();
 await page.locator('[data-ma-mode="indicators"]').click();
 assert.equal(await page.locator('#maLegacyWorkspace').getAttribute('open'),'');
 assert.equal(await page.locator('#maLegacyWorkspace .dataset-workspace').count(),1);
 assert.equal(await page.locator('#maLegacyWorkspace input[type=file]').count(),1);
 await page.goto(host+'/#data?seccion=data-plan-estadistico',{waitUntil:'domcontentloaded'});
 await page.locator('#peHome').waitFor({state:'visible'});
 await page.goto(host+'/#data?seccion=data-conoce',{waitUntil:'domcontentloaded'});
 await page.locator('#cn-title').waitFor({state:'visible'});
 await page.goto(host+'/#data?seccion=data-fuentes',{waitUntil:'domcontentloaded'});
 await page.locator('#d23HeroTitle').waitFor({state:'visible'});
 await page.goto(host+'/#data?seccion=data-municipales',{waitUntil:'domcontentloaded'});
 await page.locator('#maApp[data-ready=true]').waitFor({state:'visible'});
 await page.locator('[data-ma-mode="overview"]').click();
 assert.match(await page.locator('.ma-key-metrics').innerText(),/2/);
 await page.setViewportSize({width:390,height:844});
 await page.locator('#maTitle').waitFor({state:'visible'});
 assert.ok(await page.evaluate(()=>document.querySelector('#maApp').scrollWidth <= window.innerWidth+5),'archive causes horizontal overflow');
 await page.screenshot({path:path.join(shots,'memoria23-movil.png'),fullPage:true});
 assert.deepEqual(errors.filter(x=>/memoria-alcaldia|maApp|maForm|Cannot read properties/i.test(x)),[],'Archive runtime errors');
 console.log('MEMORIA 2.3 BROWSER: PASS — import, storage, docs, history, search, CSV, edit, graphs, responsive and legacy sections.');
 if(errors.length)console.log('Other page errors:',errors.slice(0,8));
 }finally{await browser.close();}
}
run().then(()=>server.close()).catch(error=>{console.error(error);server.close();process.exitCode=1;});
