/* DANE 2.3 Subachoque: pruebas de datos, renderizadores y no regresión. */
'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname,'..');
const read = rel => fs.readFileSync(path.join(root,rel),'utf8');
const html = read('index.html');
const css = read('css/dane-subachoque.css');
const chartsJs = read('js/dane-subachoque-charts.js');
const appJs = read('js/dane-subachoque.js');
const data = JSON.parse(read('data/dane-subachoque-cnpv.json'));
const geo = JSON.parse(read('data/veredas-subachoque.geojson'));
assert.equal(data.municipality,'Subachoque');
assert.equal(data.daneCode,'25769');
assert.match(data.source.url,/^https:\/\/sitios\.dane\.gov\.co\/cnpv\/.*25769\.pdf$/);
assert.equal(data.census.length,2);
assert.deepEqual(data.census.map(row=>row.year),[2005,2018]);
assert.deepEqual(data.census.map(row=>row.total),[12972,14874]);
assert.deepEqual(data.census.map(row=>row.households),[3522,4839]);
for(const row of data.census)assert.equal(row.urban+row.rural,row.total,'municipal total must reconcile');
assert.equal(data.census[1].urban,7217);
assert.equal(data.census[1].rural,7657);
assert.equal(data.services2018.length,6);
assert.ok(data.services2018.every(x=>Number.isFinite(x.percent)&&x.percent>=0&&x.percent<=100));
const sum = items=>items.reduce((s,x)=>s+x,0);
assert.ok(Math.abs(sum(data.agePercent2018.map(x=>x.value))-100)<.0001);
assert.ok(Math.abs(sum(data.householdSizePercent2018.map(x=>x.value))-100)<.001);
assert.ok(Math.abs(sum(data.pyramid2018.flatMap(x=>[x.men,x.women]))-100)<.5,'rounding may deviate slightly');
assert.ok(data.sourceLinks.every(x=>new URL(x.url).protocol==='https:'));
assert.equal(data.explanatoryVideoUrl,'');
assert.equal(geo.features.length,17);
assert.ok(geo.features.every(x=>x.properties.nombre&&['Polygon','MultiPolygon'].includes(x.geometry.type)));
new Function(chartsJs);
new Function(appJs);
const sandbox={window:{},Intl,Number,String,Array,Object,Math,Set,Map};
vm.runInNewContext(chartsJs,sandbox,{filename:'dane-subachoque-charts.js'});
const C=sandbox.window.TIDaneCharts;
assert.ok(C,'visualizer must expose renderer functions');
const trend=C.trend(data.census);
const donut=C.donut([{name:'Cabecera',value:7217},{name:'Resto',value:7657}],'14874','personas');
const pyramid=C.pyramid(data.pyramid2018);
const bars=C.serviceBars(data.services2018);
const household=C.verticalBars(data.householdSizePercent2018);
const map=C.geometry(geo);
for(const [name,markup] of Object.entries({trend,donut,pyramid,bars,household,map}))assert.ok(markup.length>150,'empty visual '+name);
assert.equal((map.match(/data-d23-vereda="/g)||[]).length,17);
assert.equal((pyramid.match(/class="d23-graphic"/g)||[]).length,1);
assert.ok(!/18\.259/.test(JSON.stringify(data)),'Do not reuse mockup invented value as DANE fact');
for(const label of ['2.3 Datos del DANE','2.1 Conoce','2.2 Plan Estadístico Municipal'])
  assert.ok(html.includes(label),'missing navigation label '+label);
assert.ok(html.includes('id="d23App"')&&html.includes('id="d23LegacyViewer"'));
assert.ok(html.includes('assets/interactive/data-fuentes-visor.html'),'Original viewer removed');
assert.ok(html.includes('js/dane-subachoque-charts.js?v=dane23-01'));
assert.ok(html.includes('js/dane-subachoque.js?v=dane23-01'));
assert.ok(html.includes('css/dane-subachoque.css?v=dane23-01'));
assert.ok(css.includes('#data-fuentes .d23-hero'));
assert.ok(css.includes('overflow-y:auto!important'),'the page must remain scrollable');
for(const id of ['data-fuentes','d23App','d23LegacyViewer','data-conoce','data-plan-estadistico']){
  assert.equal((html.match(new RegExp('id="'+id+'"','g'))||[]).length,1,'Duplicate or missing ID: '+id);
}
for(const feature of ['poblacion','series','mapas','fuentes'])assert.ok(appJs.includes('["'+feature+'"'));
console.log('DANE 2.3 CHECK: OK - Subachoque 2005/2018, 17 veredas, 6 services, 6 charts, legacy preserved.');
