/* Memoria de la Alcaldía: sin documentos ficticios y sin pérdida del módulo anterior. */
'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const base=path.resolve(__dirname,'..');
const read=x=>fs.readFileSync(path.join(base,x),'utf8');
const html=read('index.html'),js=read('js/memoria-alcaldia.js'),css=read('css/memoria-alcaldia.css');
new Function(js);
assert.equal((html.match(/id="data-municipales"/g)||[]).length,1);
assert.equal((html.match(/id="maApp"/g)||[]).length,1);
assert.equal((html.match(/id="maLegacyWorkspace"/g)||[]).length,1);
assert.equal((html.match(/data-dataset-workspace="municipales"/g)||[]).length,1);
for(const name of ['data-conoce','data-plan-estadistico','data-fuentes','data-municipales','data-encuesta'])assert.ok(html.includes('id="'+name+'"'),name+' missing');
assert.ok(html.includes('2.3 Memoria de la Alcaldía'),'Approved display numbering missing');
for(const file of ['css/memoria-alcaldia.css','js/memoria-alcaldia.js'])assert.ok(html.includes(file),file+' missing');
for(const x of ['.ma-hero','.ma-search','.ma-features','.ma-panel','.ma-donut','.ma-doc-table','.ma-form','.ma-feature'])assert.ok(css.includes(x),'missing style '+x);
for(const name of ['documents','dependencies','history','indicators'])assert.ok(js.includes('"'+name+'"'),'missing feature '+name);
for(const flag of ['TIData.read(KEY)','TIData.write(KEY','new FormData(form)','new Blob([content]','crypto.randomUUID()','confirm(','fileBlob'])assert.ok(js.includes(flag),'missing real capability '+flag);
assert.ok(js.includes('maxBytes=25*1024*1024'),'no upload bound');
assert.ok(js.includes('location')===false||js.includes("ma-hero-location"));
assert.ok(!/\b(12\.842|5\.360|42\.860|836\s*GB|28\.940|1\.842)\b/.test(js),'mockup figures must not appear as real data');
assert.match(js,/No fue posible leer el archivo/);
assert.ok(js.includes('DEMOSTRACIÓN VISUAL')&&js.includes('REPOSITORIO LOCAL'),'Must distinguish demo versus real persistence');
assert.ok(css.includes('memoria-aprobada.webp'),'Approved reference image must be used');
assert.ok(js.includes('ma-grid-analytics')&&js.includes('ma-grid-doc-history'),'Approved three-panel and two-panel layout must be present');
assert.ok(!js.includes('jorge-alberto-camacho')&&!js.includes('heroLocalVideo'),'Mayor video must never be embedded');

const demoSource=read('js/memoria-alcaldia-demo.js');
new Function(demoSource);
const vm=require('node:vm');
const sandbox={window:{},Intl,Number,Object,Array,Map,Set,String,Error};
vm.runInNewContext(demoSource,sandbox,{filename:'memoria-alcaldia-demo.js'});
const D=sandbox.window.TI_MA_DEMO;
assert.ok(D,'Demo component loaded');
assert.equal(D.data.metrics.documents,5253);
assert.equal(D.data.metrics.digitized,3572);
assert.equal(D.data.metrics.pending,1681);
assert.equal(D.data.metrics.digitizedPercent,68);
assert.equal(D.data.metrics.pendingPercent,32);
assert.equal(D.data.metrics.departments,11);
assert.equal(D.data.metrics.firstYear,1984);
assert.equal(D.data.metrics.lastYear,2024);
assert.equal(D.data.departments.length,9);
assert.equal(D.data.departments.reduce((total,r)=>total+r.value,0),5253);
assert.equal(D.data.docs.length,5);
assert.equal(D.data.events.length,6);
assert.match(D.archiveStatus(),/68%/);
assert.match(D.archiveStatus(),/32%/);
assert.match(D.keyMetrics(),/5\.253/);
assert.match(D.keyMetrics(),/3\.572/);
assert.match(D.keyMetrics(),/\+12%/);
assert.match(D.keyMetrics(),/\+18%/);
assert.match(D.documentsList(),/demo-acuerdo/);
assert.match(D.timeline(),/1984/);
assert.match(D.timeline(),/2024/);
assert.equal(D.filteredDocs({q:"presupuestal"}).length,1);
assert.ok(html.includes('memoria-alcaldia-demo.js?v=memoria23-demo-01'));
assert.ok(html.indexOf('js/memoria-alcaldia-demo.js')<html.indexOf('js/memoria-alcaldia.js'),'Load demo before the application');
assert.ok(js.includes('state.demoMode=savedViewMode()!=="real";'),'Demo is default unless user explicitly chose real mode');
assert.ok(js.includes('rememberViewMode()'),'Selected demo or real view mode persists');
assert.ok(js.includes('state.demoMode=false;rememberViewMode();state.error='),'Saved real documents switch to live and retain the selected view');
assert.ok(js.includes('if(state.demoMode)return demo.dashboard(panel,state.filters)'),'Demo board must be isolated');
assert.ok(js.includes('data-ma-action="toggle-demo"'),'Visible toggle required');
assert.ok(css.includes('ma-demo-key-metrics')&&css.includes('ma-demo-timeline'),'Demo styles required');

console.log('MEMORIA 2.3 STATIC: PASS — chart components, CRUD, uploads, source labels, isolated legacy workspace.');
